config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  scope path: ApplicationResource.endpoint_namespace, defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      get "/current_user" => "users#show"

      resources :memberships

      resources :teams

      resources :topics

      resources :messages

      resources :rooms

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "rooms#index"
  resources :memberships
  resources :teams
  resources :topics
  resources :messages
  resources :rooms
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ApplicationRecord
  # Direct associations

  has_many   :messages,
             dependent: :destroy

  belongs_to :room

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    room.to_s
  end
end

app/controllers/api/v1/topics_controller.rb
class Api::V1::TopicsController < Api::V1::GraphitiController
  def index
    topics = TopicResource.all(params)
    respond_with(topics)
  end

  def show
    topic = TopicResource.find(params)
    respond_with(topic)
  end

  def create
    topic = TopicResource.build(params)

    if topic.save
      render jsonapi: topic, status: :created
    else
      render jsonapi_errors: topic
    end
  end

  def update
    topic = TopicResource.find(params)

    if topic.update_attributes
      render jsonapi: topic
    else
      render jsonapi_errors: topic
    end
  end

  def destroy
    topic = TopicResource.find(params)

    if topic.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: topic
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: %i[show edit update destroy]

  def index
    @q = Topic.ransack(params[:q])
    @topics = @q.result(distinct: true).includes(:room, :messages).page(params[:page]).per(10)
  end

  def show
    @message = Message.new
  end

  def new
    @topic = Topic.new
  end

  def edit; end

  def create
    @topic = Topic.new(topic_params)

    if @topic.save
      message = "Topic was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @topic, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @topic.update(topic_params)
      redirect_to @topic, notice: "Topic was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @topic.destroy
    message = "Topic was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to topics_url, notice: message
    end
  end

  private

  def set_topic
    @topic = Topic.find(params[:id])
  end

  def topic_params
    params.require(:topic).permit(:room_id, :name)
  end
end

app/views/topics/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Topic #<%= topic.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Room</dt>
      <dd>
        <% if @topic.room.present? %>
          <%= link_to topic.room, topic.room %>
        <% end %>
      </dd>

      <dt>Name</dt>
      <dd><%= topic.name %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back topic, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_topic_url(topic), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to topic, method: :delete, data: { confirm: "Do you really want to delete this topic?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(topic.updated_at) %> ago
  </div>
</div>

app/views/topics/_form.html.erb
<% was_validated = topic.errors.any? %>

<%= form_with(model: topic, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% room_class = "form-control" %>
    <% room_was_invalid = topic.errors.include?(:room) %>

    <% if was_validated %>
      <% if room_was_invalid %>
        <% room_class << " is-invalid" %>
      <% else %>
        <% room_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :room_id %>
    <%= f.collection_select :room_id, Room.all, :id, :to_s, {}, class: "form-control" %>
    <% if room_was_invalid %>
      <% topic.errors.full_messages_for(:room).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% name_class = "form-control" %>
    <% name_was_invalid = topic.errors.include?(:name) %>

    <% if was_validated %>
      <% if name_was_invalid %>
        <% name_class << " is-invalid" %>
      <% else %>
        <% name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name, class: name_class, placeholder: "Enter name" %>
    <% if name_was_invalid %>
      <% topic.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/topics/_list_item.html.erb
<%= link_to topic, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= topic %>
    <small class="text-muted">
      <%= time_ago_in_words(topic.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/topics/_topic_messages.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Messages

    <a data-toggle="collapse" href="#topic_messages_new_form">
      Add message
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @topic.messages.each do |message| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to message, message_path(message) %>

        <% if current_user == message.user %>
          <%= link_to message, method: :delete do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="topic_messages_new_form">
        <%= render partial: "topics/topic_messages_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/topics/_topic_messages_new_form.html.erb
<%= form_with(model: @message, local: true) do |f| %>

  <%= f.hidden_field :topic_id, value: @topic.id %>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: "3", class: "form-control" %>
  </div>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <%= f.submit "Create message", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/topics/_topics_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "topics_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :name_cont, "Name contains" %>
    <%= f.text_field :name_cont, :class => "form-control", :placeholder => "Name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :room_name_cont, "Room name contains" %>
    <%= f.text_field :room_name_cont, :class => "form-control", :placeholder => "Room name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/topics" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#topics_filters">
  Show filters
</a>

app/views/topics/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Topic #<%= @topic.id %>
      </h2>

      <div class="card-body">
        <%= render "form", topic: @topic %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/topics/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Topics

      <%= link_to new_topic_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "topics/topics_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Topics

        <%= link_to new_topic_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @topics, partial: "list_item", as: :topic %>
      </div>
    </div>
  </div>
</div>

app/views/topics/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Topic
      </h2>

      <div class="card-body">
        <%= render "form", topic: @topic %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/topics/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @topic, partial: "card", as: :topic %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "topics/topic_messages" %>
  </div>
</div>