config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  scope path: ApplicationResource.endpoint_namespace, defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      get "/current_user" => "users#show"

      resources :memberships

      resources :teams

      resources :topics

      resources :messages

      resources :rooms

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "rooms#index"
  resources :memberships
  resources :teams
  resources :topics
  resources :messages
  resources :rooms
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Direct associations
  has_many :access_grants,
           class_name: "Doorkeeper::AccessGrant",
           foreign_key: :resource_owner_id,
           dependent: :delete_all # or :destroy if you need callbacks

  has_many :access_tokens,
           class_name: "Doorkeeper::AccessToken",
           foreign_key: :resource_owner_id,
           dependent: :delete_all # or :destroy if you need callbacks

  has_many   :memberships,
             dependent: :destroy

  has_many   :rooms,
             foreign_key: "creator_id",
             dependent: :nullify

  has_many   :messages,
             dependent: :nullify

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    username
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::GraphitiController
  def index
    users = UserResource.all(params)
    respond_with(users)
  end

  def show
    base_scope = params[:id].blank? ? User.where(id: current_resource_owner) : User.all
    user = UserResource.find(params, base_scope)
    respond_with(user)
  end

  def create
    user = UserResource.build(params)

    if user.save
      render jsonapi: user, status: :created
    else
      render jsonapi_errors: user
    end
  end

  def update
    user = UserResource.find(params)

    if user.update_attributes
      render jsonapi: user
    else
      render jsonapi_errors: user
    end
  end

  def destroy
    user = UserResource.find(params)

    if user.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: user
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.page(params[:page]).per(10)
  end

  def show
    @membership = Membership.new
    @room = Room.new
    @message = Message.new
  end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: "User was successfully created."
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "User was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: "User was successfully destroyed."
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username)
  end
end

app/views/users/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    User #<%= user.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Username</dt>
      <dd><%= user.username %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back user, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_user_url(user), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to user, method: :delete, data: { confirm: "Do you really want to delete this user?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(user.updated_at) %> ago
  </div>
</div>

app/views/users/_form.html.erb
<% was_validated = user.errors.any? %>

<%= form_with(model: user, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% username_class = "form-control" %>
    <% username_was_invalid = user.errors.include?(:username) %>

    <% if was_validated %>
      <% if username_was_invalid %>
        <% username_class << " is-invalid" %>
      <% else %>
        <% username_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :username %>
    <%= f.text_field :username, class: username_class, placeholder: "Enter username" %>
    <% if username_was_invalid %>
      <% user.errors.full_messages_for(:username).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/users/_list_item.html.erb
<%= link_to user, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= user %>
    <small class="text-muted">
      <%= time_ago_in_words(user.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/users/_user_memberships.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Memberships

    <a data-toggle="collapse" href="#user_memberships_new_form">
      Add membership
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @user.memberships.each do |membership| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to membership, membership_path(membership) %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="user_memberships_new_form">
        <%= render partial: "users/user_memberships_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/users/_user_memberships_new_form.html.erb
<%= form_with(model: @membership, local: true) do |f| %>

  <%= f.hidden_field :user_id, value: @user.id %>

  <div class="form-group">
    <%= f.label :team_id %>
    <%= f.collection_select :team_id, Team.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :role %>
    <%= f.select :role, options_for_select(Membership.roles.keys), {}, class: "form-control" %>
  </div>

  <%= f.submit "Create membership", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/users/_user_messages.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Messages

    <a data-toggle="collapse" href="#user_messages_new_form">
      Add message
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @user.messages.each do |message| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to message, message_path(message) %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="user_messages_new_form">
        <%= render partial: "users/user_messages_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/users/_user_messages_new_form.html.erb
<%= form_with(model: @message, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :topic_id %>
    <%= f.collection_select :topic_id, Topic.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: "3", class: "form-control" %>
  </div>

  <%= f.hidden_field :user_id, value: @user.id %>

  <%= f.submit "Create message", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/users/_user_rooms.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Rooms

    <a data-toggle="collapse" href="#user_rooms_new_form">
      Add room
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @user.rooms.each do |room| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to room, room_path(room) %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="user_rooms_new_form">
        <%= render partial: "users/user_rooms_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/users/_user_teams.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Teams
  </div>

  <ul class="list-group list-group-flush">
    <% @user.teams.each do |team| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/teams/<%= team.id %>">
          <%= team %>
        </a>

      </li>
    <% end %>

  </ul>
</div>

app/views/users/_users_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "users_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :username_cont, "Username contains" %>
    <%= f.text_field :username_cont, :class => "form-control", :placeholder => "Username contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :rooms_name_cont, "Room name contains" %>
    <%= f.text_field :rooms_name_cont, :class => "form-control", :placeholder => "Room name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :teams_name_cont, "Team name contains" %>
    <%= f.text_field :teams_name_cont, :class => "form-control", :placeholder => "Team name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/users" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#users_filters">
  Show filters
</a>

app/views/users/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit User #<%= @user.id %>
      </h2>

      <div class="card-body">
        <%= render "form", user: @user %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Users

      <%= link_to new_user_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>






<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Users

        <%= link_to new_user_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @users, partial: "list_item", as: :user %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New User
      </h2>

      <div class="card-body">
        <%= render "form", user: @user %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @user, partial: "card", as: :user %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "users/user_messages" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "users/user_rooms" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "users/user_memberships" %>
  </div>
</div>