config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  scope path: ApplicationResource.endpoint_namespace, defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      get "/current_user" => "users#show"

      resources :memberships

      resources :teams

      resources :topics

      resources :messages

      resources :rooms

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "rooms#index"
  resources :memberships
  resources :teams
  resources :topics
  resources :messages
  resources :rooms
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  # Direct associations

  belongs_to :team,
             counter_cache: true

  has_many   :topics,
             dependent: :destroy

  belongs_to :creator,
             optional: true,
             class_name: "User"

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    name
  end
end

app/controllers/api/v1/rooms_controller.rb
class Api::V1::RoomsController < Api::V1::GraphitiController
  def index
    rooms = RoomResource.all(params)
    respond_with(rooms)
  end

  def show
    room = RoomResource.find(params)
    respond_with(room)
  end

  def create
    room = RoomResource.build(params)

    if room.save
      render jsonapi: room, status: :created
    else
      render jsonapi_errors: room
    end
  end

  def update
    room = RoomResource.find(params)

    if room.update_attributes
      render jsonapi: room
    else
      render jsonapi_errors: room
    end
  end

  def destroy
    room = RoomResource.find(params)

    if room.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: room
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[show edit update destroy]

  def index
    @q = Room.ransack(params[:q])
    @rooms = @q.result(distinct: true).includes(:creator, :topics, :team).page(params[:page]).per(10)
  end

  def show
    @topic = Topic.new
  end

  def new
    @room = Room.new
  end

  def edit; end

  def create
    @room = Room.new(room_params)

    if @room.save
      message = "Room was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @room, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @room.update(room_params)
      redirect_to @room, notice: "Room was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @room.destroy
    message = "Room was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to rooms_url, notice: message
    end
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:name, :anyone_can_join, :creator_id, :team_id, :hidden)
  end
end

app/views/rooms/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Room #<%= room.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Name</dt>
      <dd><%= room.name %></dd>

      <dt>Anyone can join</dt>
      <dd><%= room.anyone_can_join %></dd>

      <dt>Creator</dt>
      <dd>
        <% if @room.creator.present? %>
          <%= link_to room.creator, room.creator %>
        <% end %>
      </dd>

      <dt>Team</dt>
      <dd>
        <% if @room.team.present? %>
          <%= link_to room.team, room.team %>
        <% end %>
      </dd>

      <dt>Hidden</dt>
      <dd><%= room.hidden %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back room, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_room_url(room), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to room, method: :delete, data: { confirm: "Do you really want to delete this room?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(room.updated_at) %> ago
  </div>
</div>

app/views/rooms/_form.html.erb
<% was_validated = room.errors.any? %>

<%= form_with(model: room, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% name_class = "form-control" %>
    <% name_was_invalid = room.errors.include?(:name) %>

    <% if was_validated %>
      <% if name_was_invalid %>
        <% name_class << " is-invalid" %>
      <% else %>
        <% name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name, class: name_class, placeholder: "Enter name" %>
    <% if name_was_invalid %>
      <% room.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-check">
    <% anyone_can_join_class = "form-check-input" %>
    <% anyone_can_join_was_invalid = room.errors.include?(:anyone_can_join) %>

    <% if was_validated %>
      <% if anyone_can_join_was_invalid %>
        <% anyone_can_join_class << " is-invalid" %>
      <% else %>
        <% anyone_can_join_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :anyone_can_join, class: "form-check-label" do %>
      <%= f.check_box :anyone_can_join, class: anyone_can_join_class %> Anyone can join
    <% end %>
    <% if anyone_can_join_was_invalid %>
      <% room.errors.full_messages_for(:anyone_can_join).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.hidden_field :creator_id, value: current_user.id %>
  <div class="form-group">
    <% team_class = "form-control" %>
    <% team_was_invalid = room.errors.include?(:team) %>

    <% if was_validated %>
      <% if team_was_invalid %>
        <% team_class << " is-invalid" %>
      <% else %>
        <% team_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :team_id %>
    <%= f.collection_select :team_id, Team.all, :id, :to_s, {}, class: "form-control" %>
    <% if team_was_invalid %>
      <% room.errors.full_messages_for(:team).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-check">
    <% hidden_class = "form-check-input" %>
    <% hidden_was_invalid = room.errors.include?(:hidden) %>

    <% if was_validated %>
      <% if hidden_was_invalid %>
        <% hidden_class << " is-invalid" %>
      <% else %>
        <% hidden_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :hidden, class: "form-check-label" do %>
      <%= f.check_box :hidden, class: hidden_class %> Hidden
    <% end %>
    <% if hidden_was_invalid %>
      <% room.errors.full_messages_for(:hidden).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/rooms/_list_item.html.erb
<%= link_to room, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= room %>
    <small class="text-muted">
      <%= time_ago_in_words(room.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/rooms/_room_topics.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Topics

    <a data-toggle="collapse" href="#room_topics_new_form">
      Add topic
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @room.topics.each do |topic| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to topic, topic_path(topic) %>

        <%= link_to topic, method: :delete, data: { confirm: "Do you really want to delete this topic" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="room_topics_new_form">
        <%= render partial: "rooms/room_topics_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/rooms/_room_topics_new_form.html.erb
<%= form_with(model: @topic, local: true) do |f| %>

  <%= f.hidden_field :room_id, value: @room.id %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <%= f.submit "Create topic", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/rooms/_rooms_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "rooms_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :name_cont, "Name contains" %>
    <%= f.text_field :name_cont, :class => "form-control", :placeholder => "Name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :hidden_eq, "Hidden" %>
    <div>
      <label class="radio-inline">
        <%= f.radio_button :hidden_eq, "1", checked: ((params[:q] && params[:q][:hidden_eq]) == "1" ? "checked" : "") %> Yes
      </label>
      <label class="radio-inline">
        <%= f.radio_button :hidden_eq, "0", checked: ((params[:q] && params[:q][:hidden_eq]) == "0" ? "checked" : "")%> No
      </label>
      <label class="radio-inline">
        <%= f.radio_button :hidden_eq, ""%> Either
      </label>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :anyone_can_join_eq, "Anyone can join" %>
    <div>
      <label class="radio-inline">
        <%= f.radio_button :anyone_can_join_eq, "1", checked: ((params[:q] && params[:q][:anyone_can_join_eq]) == "1" ? "checked" : "") %> Yes
      </label>
      <label class="radio-inline">
        <%= f.radio_button :anyone_can_join_eq, "0", checked: ((params[:q] && params[:q][:anyone_can_join_eq]) == "0" ? "checked" : "")%> No
      </label>
      <label class="radio-inline">
        <%= f.radio_button :anyone_can_join_eq, ""%> Either
      </label>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :creator_username_cont, "User username contains" %>
    <%= f.text_field :creator_username_cont, :class => "form-control", :placeholder => "User username contains" %>
  </div>

  <div class="form-group">
    <%= f.label :team_name_cont, "Team name contains" %>
    <%= f.text_field :team_name_cont, :class => "form-control", :placeholder => "Team name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/rooms" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#rooms_filters">
  Show filters
</a>

app/views/rooms/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Room #<%= @room.id %>
      </h2>

      <div class="card-body">
        <%= render "form", room: @room %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Rooms

      <%= link_to new_room_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "rooms/rooms_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Rooms

        <%= link_to new_room_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @rooms, partial: "list_item", as: :room %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Room
      </h2>

      <div class="card-body">
        <%= render "form", room: @room %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @room, partial: "card", as: :room %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "rooms/room_topics" %>
  </div>
</div>